apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary
  name: canary-v1
  namespace: udacity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: configmap-vol
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: configmap-vol
          configMap:
            name: canary-config-v1
---
apiVersion: v1
kind: Service
metadata:
  name: canary
  namespace: udacity
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: canary
  type: LoadBalancer

